### Q1: (Printing and Input)
Print your name and age using two print statements.

In [3]:
name =  "Subhash Kumar Thakur "
age =  23

print("Name:", name)
print("Age:", age)

Name: Subhash Kumar Thakur 
Age: 23


### Q2: (Printing and Input)
Print the result of 10 + 20.

In [ ]:
print("The Sum is 10+20:", 10+20)


# if take input from user.
# Num1 = int(input("Enter First number: "))
# Num2 = int(input("Enter Second number: "))
# print("The Sum is", Num1 + Num2)

The Sum is 10+20: 30
The Sum is 30


### Q3: (Printing and Input)
Use `input()` to take a user's name and greet them.

In [ ]:
name = input("Enter your name: ")
print("Hello ,", name)
# print("Nice to meet you!", name)

Hello , Subhash
Nice to meet you! Subhash


### Q4: (Printing and Input)
Input two numbers and print their sum.

In [ ]:
Num1 = float(input("Enter the Frist number: "))
Num2 = float(input("Enter the Second number: "))
Sum = Num1 + Num2
print("The Sum Is:", Sum)

The Sum Is: 90.50059999999999


### Q5: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [ ]:
Color = input("Enter your favorite color:")
print(Color * 2)

BlackBlack


### Q6: (Printing and Input)
Ask the user to input a sentence and print its length.

In [19]:
Sen = input("Enter the sentenece:")
print(Sen)              # sen = sentence
print("The length of the sentence is:", len(Sen))

I love you ji............
The length of the sentence is: 25


### Q7: (Variable and Data Types)
Create a variable for each type: int, float, string, bool. Print them.

In [20]:
int=10
float=9999.8
string="Hello ji"
bool=True

print("Integer:", int)
print("Float:", float)
print("String:", string)   
print("Boolean:", bool)

Integer: 10
Float: 9999.8
String: Hello ji
Boolean: True


### Q8: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [21]:
x=10
x=x+5
print(x)

15


### Q9: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [26]:
val = 3.14
print(type(val))

<class 'float'>


### Q10: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [27]:
a,b,c = 4,9,19
print(a)
print(b)
print(c)

4
9
19


### Q11: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [28]:
x=2+3j
y=4-2j
print(x+y)

(6+1j)


In [ ]:
### Q12: (Complex Numbers)
Print the real and imaginary parts of 5 + 7j.

In [29]:
S = 5+7j
print("Real part:", S.real)
print("Imaginary part:", S.imag)

Real part: 5.0
Imaginary part: 7.0


### Q13: (Complex Numbers)
Multiply two complex numbers: (1+2j)*(3+4j) and print the result.

In [30]:
x=1+2j
y=3+4j
print(x*y)

(-5+10j)


### Q14: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [ ]:

if 12 > 10:
    print("12 is greater than 10")  
else:
    print("10 is greater than 12")  


12 is greater than 10


### Q15: (If-Else and Comparisons)
Ask for an age and print whether the person is an adult or not.

In [43]:
# del int

age = int(input("Enter your age: "))
if age >= 18:
    print("You are an adult.")
else:
    print("You are not an adult.")

You are an adult.


### Q16: (If-Else and Comparisons)
Check if a number is even or odd.

In [46]:
Num = int(input("Enter a number: "))
if Num % 2 == 0:
    print("The number is even.")    
else:
    print("The number is odd.")

The number is odd.


### Q17: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [47]:
Num1 = int(input("Enter first number: "))
Num2 = int(input("Enter second number: "))  

if Num1 > Num2:
    print("First number is greater than second number.")
elif Num1 < Num2:
    print("Second number is greater than first number.")    
else:
    print("Both numbers are equal.")

Both numbers are equal.


### Q18: (Loops)
Print numbers from 1 to 10 using a for loop.

In [ ]:
for i in range(1, 11):
    print(i) 

1
2
3
4
5
6
7
8
9
10


### Q19: (Loops)
Print all even numbers from 0 to 20.

In [57]:
for i in range(2, 21,2):
    print(i) 
  

2
4
6
8
10
12
14
16
18
20


### Q20: (Loops)
Print the multiplication table of 7.

In [67]:
for i in range(1, 11):
    #print(f"7*{i}: {7*i}")  
    print( 7*i)

7
14
21
28
35
42
49
56
63
70


### Q21: (Loops)
Use a while loop to print numbers from 5 to 1.

In [72]:
i = 5
while i > 0:
    print(i)
    i -= 1  

5
4
3
2
1


### Q22: (Loops)
Print the characters of a string one by one using a loop.

In [ ]:
text = "Subhash Kumar "
for char in text:
    print(char)

S
u
b
h
a
s
h
-
K
u
m
a
r
 


### Q23: (String Operations)
Concatenate 'Hello' and 'World' and print.

In [134]:
Greeting = "Hello" +" " + "World"
print(Greeting)

Hello World


### Q24: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [135]:
print(("yes" * 4).strip())

yesyesyesyes


### Q25: (String Operations)
Find the length of a string input by user.

In [136]:
user = input("Enter a string: ")
length = len(user)
print("The length of the string is:", length)

The length of the string is: 83


### Q26: (String Operations)
Access and print the first and last character of a string.

In [138]:
user1 = input("Enter a string: ")

if len(user1) >0:
    print("Frist charcter:", user1[0])
    print("Last Character:", user1[-1])


Frist charcter: s
Last Character: h


### Q27: (Lists)
Create a list of 5 fruits and print the third item.

In [140]:
fruits = ["carrot", "guva", "pomogrante", "grape", "mango"]
print(fruits[3])

grape


### Q28: (Lists)
Add 'mango' to the list and print.

In [257]:
fruits = ["carrot", "guva", "pomogrante", "grape", "apple"]
fruits.append("mango")
print(fruits)

['carrot', 'guva', 'pomogrante', 'grape', 'apple', 'mango']




### Q29: (Lists)
Remove the first item of the list and print the rest.

In [260]:
fruits = ["carrot", "guva", "pomogrante", "grape", "apple"]
fruits.pop(0)
print(fruits)

['guva', 'pomogrante', 'grape', 'apple']


### Q30: (Lists)
Sort a list of numbers in descending order.

In [262]:
nums = [10, 5, 8, 12, 3]
nums.sort(reverse=True)
print(nums)


[12, 10, 8, 5, 3]


### Q31: (Lists)
Print every second item from a list using slicing.

In [265]:
list = [10, 20, 70, 40, 90, 60, 100]
print(list[::2])
# in slicing skip the one item 

[10, 70, 90, 100]


### Q32: (Tuples)
Create a tuple with 4 numbers and print its last item.

In [ ]:
del list
tuple = (10, 30, 40, 90)
list = list(tuple)
print(list)

#A tuple is immutable, which means once created,
# its elements cannot be changed, added, or removed.


[10, 30, 40, 90]


### Q33: (Tuples)
Try changing the value of an item in a tuple and observe the error.

In [3]:
my_tuple = (10, 20, 30)
my_tuple[0] = 100  

# We try to change the first element of a tuple, 
# but since tuples are immutable, 
# their elements cannot be changed once created. 
# That’s why we get the error: “tuple object does not support item assignment.”

TypeError: 'tuple' object does not support item assignment

### Q34: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [ ]:
my_tuple = (10, 40, 30)
my_list = list(my_tuple)

my_list[1] = 99
my_tuple = tuple(my_list)
print(my_tuple)

# Convert tuple to list and replace the value 40 with 99


(10, 99, 30)


### Q35: (Sets)
Create a set of 3 elements and add one more element.

In [286]:
set = {"apple","miss", "jiiiii"}
set.add("piiiiiiiii")
print(set)

{'apple', 'piiiiiiiii', 'jiiiii', 'miss'}


### Q36: (Sets)
Try adding a duplicate and print the set.

In [ ]:
set = {"apple","miss", "jiiiii"}
set.add("miss")
print(set)
# Sets automatically ignore duplicate values,
# So adding a duplicate does not change the set.


{'apple', 'jiiiii', 'miss'}


### Q37: (Sets)
Perform union of two sets {1,2,3} and {3,4,5}.

In [288]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}


union_set = set1.union(set2)

print(union_set)


{1, 2, 3, 4, 5}


### Q38: (Dictionaries)
Create a dictionary for a student with name, age, grade. Print the dictionary.

In [289]:
student = {
    "name": "Muni Lal Ji ",
    "age": 20,
    "grade": "A+"
}

print(student)


{'name': 'Muni Lal Ji ', 'age': 20, 'grade': 'A+'}


### Q39: (Dictionaries)
Access the age from the dictionary.

In [293]:
student = {
    "name": "Muni Lal Ji ",
    "age": 20,
    "grade": "A+"
}

print(student["age"])


20


### Q40: (Dictionaries)
Update the grade of the student.

In [294]:
student = {
    "name": "Muni Lal Ji ",
    "age": 20,
    "grade": "A+"
}
student["grade"]= "B+"
print(student)


{'name': 'Muni Lal Ji ', 'age': 20, 'grade': 'B+'}


### Q41: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [ ]:
student = {
    "name": "Muni Lal Ji",
    "age": 20,
    "grade": "A+"
}

student["subject"] = "CA"

print(student)


{'name': 'Muni Lal Ji', 'age': 20, 'grade': 'A+', 'subject': 'CA'}


### Q42: (Indexing and Slicing)
Create a list of numbers and print elements from index 1 to 4.

In [298]:
number = [10,20,40, 60, 90,110]
print(number[1:4])

[20, 40, 60]


### Q43: (Indexing and Slicing)
Access every second element in the list.

In [303]:
numbers = [10, 20, 40, 60, 90, 110]
print(numbers[::2])


[10, 40, 90]


### Q44: (Indexing and Slicing)
Print the last three characters of the string 'Programming'.

In [ ]:

text = "programming"
print(text[-3:])


ing


### Q45: (Nested Structures)
Create a nested list and print the second element of the first list.

In [314]:
nested = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
print(nested[0][1])

20


### Q46: (Nested Structures)
Create a nested dictionary and access a nested value.

In [318]:
student = {
    "name": "Subhash",
    "details": {
        "age": 24,
        "grade": "A",
        "subject": "Math"
    }
}

print(student["details"]["grade"])


A


### Q47: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [319]:
import numpy as np
subhash = np.arange(10)
print(subhash)

[0 1 2 3 4 5 6 7 8 9]


### Q48: (NumPy Basics)
Create a 2D array with shape (2,3).

In [320]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)
print("Shape:", arr.shape)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### Q49: (NumPy Basics)
Print the shape and dtype of an array.

In [321]:
print("Data type of array:", arr.dtype)

Data type of array: int64


### Q50: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [322]:
import numpy as np

values = np.linspace(1, 10, 5)
print(values)


[ 1.    3.25  5.5   7.75 10.  ]


### Q51: (NumPy Basics)
Generate a random array of shape (3,3).

In [323]:
import numpy as np

random_array = np.random.rand(3, 3)

print(random_array)


[[0.37052775 0.57057894 0.06390329]
 [0.82015794 0.05288311 0.28275268]
 [0.98836652 0.24518559 0.15479102]]


### Q52: (NumPy Basics)
Find the maximum and mean of a numpy array.

In [324]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

max_value = arr.max()

mean_value = arr.mean()

print("Maximum:", max_value)
print("Mean:", mean_value)


Maximum: 50
Mean: 30.0


### Q53: (NumPy Basics)
Access element at row 1, col 2 in a 2D array.

In [325]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])


element = arr[1, 2]

print(element)


60


### Q54: (NumPy Basics)
Flatten a 2D array.

In [255]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()
print(flat_arr)

# multi dimension to single dymension


[1 2 3 4 5 6]


### Q55: (NumPy Basics)
Stack two arrays vertically.

In [252]:
import numpy as np

arr = np.array([
    [10, 20, 30],   
    [40, 50, 60],   
    [70, 80, 90],   
    [100, 110, 120] 
])

# Slice the first two rows
sliced = arr[:2, ]


print(sliced)


[[10 20 30]
 [40 50 60]]


### Q56: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [ ]:
import numpy as np

arr = np.array([[1, 7, 3],
                [4, 5, 6],
                [7, 12, 9]])


sliced = arr[::2]  

print(sliced)


### Q57: (NumPy Basics)
Slice the first two rows of a 2D numpy array.

In [250]:
import numpy as np

arr = np.array([[1, 7, 3],
                [4, 5, 6],
                [7, 12, 9]])


sliced = arr[::2]  

print(sliced)


[[ 1  7  3]
 [ 7 12  9]]


### Q58: (NumPy Basics)
Print the shape and dtype of an array.

In [239]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)    
print("Data type:", arr.dtype)  

Shape: (2, 3)
Data type: int64


### Q59: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [238]:
print("Yes " *4)

Yes Yes Yes Yes 


### Q60: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [236]:
a,b,c = 10, 20, 40
print(a,b,c,)

10 20 40


### Q61: (Dictionaries)
Add a new key 'subject' to the dictionary.

In [235]:
student = {"name": "Subhash Kumar JI", "age": 20}

student["subject"] = "Math" 

print(student)


{'name': 'Subhash Kumar JI', 'age': 20, 'subject': 'Math'}


### Q62: (Variable and Data Types)
Assign the value 10 to x and then add 5 to it. Print the result.

In [231]:
x = 10
x = x+5
print (x)

15


### Q63: (Nested Structures)
Create a nested list and print the second element of the first list.

In [ ]:
my_list = [[10, 20, 40], [50, 90, 60], [100, 200, 400]]
print(my_list[0][2]) 

# Use two indexes like list[i][j] to access the jth item of the ith inner list.


40


### Q64: (Loops)
Print the characters of a string one by one using a loop.

In [226]:
Text  =  "Hello sir"
for char in Text:
    print(char)

H
e
l
l
o
 
s
i
r


### Q65: (Sets)
Try adding a duplicate and print the set.

In [ ]:
fruits = {"apple", "banana", "cherry"}

fruits.add("banana")

print(fruits)


{'apple', 'banana', 'cherry'}


### Q66: (NumPy Basics)
Flatten a 2D array.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,6,9]])
arr_flat = arr.flatten()
print(arr_flat)
#Flattening means converting a multi-dimensional array into a single 1D array by putting all elements in one sequence.

[1 2 3 4 6 9]


### Q67: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [220]:
Dangerous_color = input("Enter the color you want multiply:")
print((Dangerous_color + " ") *2)

dsddsdsd dsddsdsd 


### Q68: (String Operations)
Repeat the word 'Yes' 4 times using *.

In [214]:
print("Yes " * 4)

Yes Yes Yes Yes 


### Q69: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [211]:
color = input("Enter your faveroute color.")
print(color*2)

subhdsbdhsdbsdsubhdsbdhsdbsd


### Q70: (If-Else and Comparisons)
Check if a number is even or odd.

In [210]:
num = int(input("Enter The number:"))
if num%2 ==0:
    print(f"{num} is even.")
else:
    print(f"{num} is odd.")


5 is odd.


### Q71: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [ ]:
import numpy as np 
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Q72: (Loops)
Use a while loop to print numbers from 5 to 1.

In [ ]:
i = 1
while i<= 5:
    print(i)
    i +=1

0
1
2
3
4
5


### Q73: (If-Else and Comparisons)
Check if the number 12 is greater than 10 and print a message.

In [201]:
num = int(input("Enter a number: "))

if num > 10:
    print(f"{num} is greater than 10.")
else:
    print(f"{num} is not greater than 10.")


9 is not greater than 10.


### Q74: (Indexing and Slicing)
Access every second element in the list.

In [197]:
list = [10, 20, 30, 40, 50, 60, 80]

# Access every second element// skip one each item or take 2nd item 
print(list[::2])  

[10, 30, 50, 80]


### Q75: (Loops)
Use a while loop to print numbers from 5 to 1.

In [194]:
i =5
while i >=1:
    print(i)
    i -=1

5
4
3
2
1


### Q76: (Printing and Input)
Print the result of 10 + 20.

In [193]:
print("The sum is:", 10+20)

The sum is: 30


### Q77: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [191]:
color = input("Enter your favourite color: ")
print(color *2)


sdsdssdsdssdsdssdsds


### Q78: (Lists)
Remove the first item of the list and print the rest.

In [189]:
fruits = ["apple", "banana", "cherry", "mango", "orange"]

# delte 
fruits.pop(0)
print(fruits)


['banana', 'cherry', 'mango', 'orange']


### Q79: (NumPy Basics)
Use np.linspace to create 5 values from 1 to 10.

In [ ]:
import numpy as np
# 
values = np.linspace(1,10,5) #it generate number same differenv=ce each number 
# like 3.25-1 = 2.25, same as 5.5-3.25= 2.25 
print(values)

[ 1.    3.25  5.5   7.75 10.  ]


### Q80: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [186]:
x = 2 + 3j
y = 4-2j
sum = x + y
print(sum)

(6+1j)


### Q81: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [185]:
color=input("Enter your faviroute color:")
print(color*2)

subhashsubhash


### Q82: (Complex Numbers)
Create complex numbers x = 2+3j and y = 4-2j. Print their sum.

In [ ]:
x = 2 + 3j
y = 4 - 2j

sum = x + y
print(sum)

(6+1j)


### Q83: (Dictionaries)
Access the age from the dictionary.

In [172]:
person = {
    "name": "Subhash Kumar Sharma",
    "age": 25,
    "city": "Kathmandu"
}

print(person["age"])


25


### Q84: (Lists)
Create a list of 5 fruits and print the third item.

In [173]:
fruits = ["apple", "banana", "mango", "orange", "grape"]

print(fruits[2])


mango


### Q85: (NumPy Basics)
Stack two arrays vertically.

In [174]:
import numpy as np

a = np.array([1, 2, 3]) #1d arrys
b = np.array([4, 5, 6])

result = np.vstack([a, b])   # vstack is stacks arry row-wise 
# 2rows 3 column (2d verticly arras)

print(result)


[[1 2 3]
 [4 5 6]]


### Q86: (Loops)
Use a while loop to print numbers from 5 to 1.

In [175]:
for i in range(5, 0, -1):  # start at 5, end before 0, (n-1)
    print(i)


5
4
3
2
1


### Q87: (Lists)
Remove the first item of the list and print the rest.

In [176]:
fruits = ["grape", "banana", "cherry", "Mango", "orange"]
fruits.pop(3) #delte 4th coulmn 
print(fruits)

['grape', 'banana', 'cherry', 'orange']


### Q88: (Lists)
Create a list of 5 fruits and print the third item.

In [177]:
fruits = ["grape", "banana", "cherry", "Mango", "orange"]
print("The 3rd fruit is:", fruits[2])

The 3rd fruit is: cherry


### Q89: (Printing and Input)
Ask for a favorite color and print it twice using multiplication.

In [178]:
color = input("Enter your favorite color: ")
print("Your favorite color is:",color*2) 

Your favorite color is: 


### Q90: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [179]:
tuple1 = (10,20,30)
list1 = list(tuple1)
list1[2]= 600000000000000
tuple1 = tuple(list1)
print(tuple1)

(10, 20, 600000000000000)


### Q91: (NumPy Basics)
Import numpy and create a 1D array from 0 to 9.

In [180]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Q92: (Variable and Data Types)
Use multiple assignment to assign 3 values to a, b, c.

In [181]:
a,b,c = 9, 8, 7
print(a)
print(b)
print(c)    

9
8
7


### Q93: (Variable and Data Types)
Check the type of variable `val = 3.14`.

In [182]:
val = 3.14
print(type(val))    

<class 'float'>


### Q94: (Tuples)
Convert a tuple to a list, change a value, and convert it back.

In [183]:
my_tuple = (10, 20, 300)       
my_list = list(my_tuple)       

my_list[1] = 99                

my_tuple = tuple(my_list)      

print(my_tuple)

(10, 99, 300)


### Q95: (If-Else and Comparisons)
Compare two input numbers and print which is Smaller.

In [184]:
a = int(input("Enter a number: "))
b = int(input("Enter another number: "))    
if a < b:
    print(f"{a} is smaller number ")
elif a > b:
    print(f"{b} is smaller number ")
    

ValueError: invalid literal for int() with base 10: ''

### Q96: (Sets)
Try adding a duplicate and print the set.

In [ ]:
set = {1, 2, 3, 4, 5}
set.add(3)
print(set)

{1, 2, 3, 4, 5}


### Q97: (Dictionaries)
Access the age from the dictionary.

In [ ]:
person = {
    "name": "Subhash Kumar Thakur",
    "age" : 23,
    "city": "Lalitpur"
} 
print("age:", person["age"] )

age: 23


### Q98: (Lists)
Add 'mango' to the list and print.

In [ ]:
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits)

['apple', 'banana', 'cherry', 'orange']


### Q99: (Sets)
Create a set of 3 elements and add one more element.

In [ ]:
set = {1, 2, 3,}
set.add(4)
print(set  )

{1, 2, 3, 4}


### Q100: (If-Else and Comparisons)
Compare two input numbers and print which is larger.

In [ ]:
a = int(input("Enter a number: "))
b = int(input("Enter another number: "))    
if a > b:
    print(f"{a} is larger number ")
elif a < b:
    print(f"{b} is larger number ")
    

6 is larger number 
